export type Item={
    id:number;
    parentId:number;
    name:String;
}
export type Node = Item & { children: Node[] };
export const originData:Item[]=[
    {
        id:0,
        parentId:null,
        name:'生物'
    },
    {
        id:1,
        parentId:0,
        name:'动物'
    },
    {
        id:2,
        parentId:0,
        name:'植物'
    },
    {
        id:3,
        parentId:0,
        name:'微生物'
    },
    {
        id:6,
        parentId:2,
        name:'种子植物'
    },
    {
        id:7,
        parentId:2,
        name:'蕨类植物'
    },
    {
        id:8,
        parentId:4,
        name:'大象'
    },
    {
        id:9,
        parentId:4,
        name:'海豚'
    },
    {
        id:10,
        parentId:4,
        name:'猩猩'
    }
]
export const treeData:Node={
    children:[
        {
            id:1,
            parentId:0,
            name:'动物',
            children:[
                {
                    id:8,
                    parentId:4,
                    name:'大象',
                },
                {
                    id:9,
                    parentId:4,
                    name:'海豚',
                },
                {
                    id:10,
                    parentId:4,
                    name:'猩猩',
                }
            ]
        },
        {
            id:2,
            parentId:0,
            name:'植物',
            children:[
                {
                    id:6,
                    parentId:2,
                    name:'种子植物'
                },
                {
                    id:7,
                    parentId:2,
                    name:'蕨类植物'
                },
            ]
        },
    ]
}